### PR TITLE
sysdump provider

### PR DESCRIPTION
**Pull request by christopherousseau**
sysdumpdev provider LWRP added

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @christopherousseau

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chmod666org** [comment]
Need your resource file sysdump.rb and modification of readme file before pull request can be accepted. Maybe adding savecore with a save action will be great too. Waiting for your input

**Comment by chmod666org** [comment]
@christopherousseau Any news on this, are still working on this provider, please let me know asap.

**Comment by chmod666org** [comment]
No answer for more than 3 months. Closing

**Pull request closed without merging**
