### PR TITLE
Adding tunables LWRP

### PR DESCRIPTION
**Pull request by adejoux**
Hello,

I created a LWRP to manage generic tunables commands ioo, vmo and schedo. 

Here a example output when running the example I provided in README :
~~~
root@adxlpar1(/tools/chef)# chef-solo -c solo.rb -j test.json              
[2015-08-24T17:54:30+02:00] WARN: Please install an English UTF-8 locale for Chef to use, falling back to C locale and disabling UTF-8 support.
Starting Chef Client, version 12.4.1
Compiling Cookbooks...
Converging 4 resources
Recipe: aix::default
  * aix_tunables[reset schedo values] action reset_all
    - schedo : resetting all
  * aix_tunables[change vpm_throughput_mode] action update
    - schedo: setting tunable vpm_throughput_mode=2
  * aix_tunables[change posix AIO servers] action update
    - ioo: setting tunable posix_aio_minservers=6
    - ioo: setting tunable posix_aio_maxservers=36
  * aix_tunables[tune minperm%] action update
    - vmo: setting tunable minperm%=6

Running handlers:
Running handlers complete
Chef Client finished, 4/4 resources updated in 6.027071 seconds
~~~

Running it again :

~~~
root@adxlpar1(/tools/chef)# chef-solo -c solo.rb -j test.json
[2015-08-24T17:54:48+02:00] WARN: Please install an English UTF-8 locale for Chef to use, falling back to C locale and disabling UTF-8 support.
Starting Chef Client, version 12.4.1
Compiling Cookbooks...
Converging 4 resources
Recipe: aix::default
  * aix_tunables[reset schedo values] action reset_all
    - schedo : resetting all
  * aix_tunables[change vpm_throughput_mode] action update
    - schedo: setting tunable vpm_throughput_mode=2
  * aix_tunables[change posix AIO servers] action update (up to date)
  * aix_tunables[tune minperm%] action update (up to date)

Running handlers:
Running handlers complete
Chef Client finished, 2/4 resources updated in 5.837877 seconds
~~~

Say if you want me to change anything in it. 

Regards,

Alain

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @adejoux

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by chmod666org** [comment]
@adejoux Is there anything that differ between no and ioo,vmo and schedo. If not I think we need to merge my no LWRP with this one. No need to have no for one and tunables for others.

**Comment by adejoux** [comment]
@chmod666org Hello. Nothing. Commands parameters are identical.  I used your no module to understand how to create a LWRP so I didn't want to replace it :)

**Comment by chmod666org** [comment]
@adejoux Ok, we can keep both as both are working, users will decide what they want.
@juliandunn Is there any possibility to allow one of us managing this cookbook, we are a couple of guys working on it and we really want to contribute to this cookbook ... I think you'll have more and more pull request and we need reactivity. What do you think about it ?

**Comment by juliandunn** [comment]
@chmod666org I think we can probably do that (hand out a commit bit) and it looks like you have way more AIX experience than I :-) I am asking internally on the procedure for doing so & I'll let you know.

**Comment by adejoux** [comment]
@chmod666org thanks but it's my first pull request and first lwrp. So I prefer to skip on managing the cookbook :) Let see if my pull request is good for now ^^

@juliandunn I am not sure if it's a good practice to define methods inside a LWRP provider. It's working here but not sure if it's something I should do.

**Comment by juliandunn** [comment]
You can define methods inside a provider but it's best to make them private.

**Comment by chmod666org** [comment]
@juliandunn OK awesome ! Thank you !
@adejoux Have methods in some of mine. Best practice is to use foodcritic before commit. (Have a look here http://acrmp.github.io/foodcritic/)

**Comment by adejoux** [comment]
@chmod666org Thanks. I didn't know about foodcritic :) Will use it now. I didn't have any issue found in my code :)

**Comment by juliandunn** [comment]
@chmod666org I added you to the collaborators list on this cookbook and transferred it to `chef-cookbooks` which is where we are consolidating all cookbooks. Send me your `supermarket.chef.io` username and I will also add you as a maintainer so you can upload new versions.

**Comment by chmod666org** [comment]
@juliandunn Thank you for your quick answer. Just joined the organization.
My supermarket.chef.io username is chmod666org

**Comment by juliandunn** [comment]
@chmod666org ok, you can also release new versions on Supermarket.

**Comment by chmod666org** [comment]
@juliandunn Great thank you
@adejoux Will check you code asap

**Pull request merged**
