### PR TITLE
updated subsystem resource to work with chef 13

### PR DESCRIPTION
**Pull request by thomascate**
### Description

Fixing subsystem resource to use newer resources.

### Issues Resolved

Current resource failed on chef 13

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by thomascate** [comment]
Not quite ready to merge yet, still needs more testing.

**Comment by tas50** [comment]
@thomascate Any chance you can rebase this and sign it off for the DCO so we can merge it?

**Comment by thomascate** [comment]
rebased and DCO sign off added

**Comment by tas50** [comment]
Thanks

**Pull request merged**
