### PR TITLE
Vendor the aix-wpar gem to avoid the need to install it from rubygems

### PR DESCRIPTION
**Pull request by vsingh-msys**
### Description
Adding aix-wpar gem in vendor in order to avoid manual installation. Also lib https://github.com/adejoux/aix-wpar seems to be dead so forked this lib into chef org https://github.com/chef/aix-wpar and resolved some the issues.

- build local gem `aix-wpar-0.2.0.gem`.
- install it using into vendor dir.

```
gem install --install-dir files/default/vendor --no-user-install ../../aix-wpar/aix-wpar-0.2.0.gem
``` 

- update load_path to require the lib [Pending for now]

### Issues Resolved
NA

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>
Signed-off-by: Vivek Singh <vivek.singh@msystechnologies.com>

### CODE REVIEW

**Comment by btm** [comment]
it looks like you have both the gem packages in `files/default` as well as unpacked copies of the gems. I don't think we need this? We should be okay with just the gem package, and then modifying `libraries/wpar.rb`. Have a cookbook_file resource put the gem somewhere and then pass that path to chef_gem via the source property.

**Comment by vsingh-msys** [comment]
`gem install` did for us and these are auto-generated. I have taken the reference from etcd cookbook https://github.com/chef-cookbooks/etcd/tree/master/files/default/vendor

**Comment by vsingh-msys** [comment]
@btm validating the stuff will update the PR accordingly. Thanks

**Comment by vsingh-msys** [comment]
@btm I have cleanup the cache copy of gem files. Managing dependency to install and load lib from `files/default/vendor` is working as per my expectation.

Also added cookstyle fixes here.
Could you please have a look again. 

if you sold on with current implementation, will update the README and steps to test?

**Comment by vsingh-msys** [comment]
@tas50 & @lamont-granquist good to have your thoughts on this as well?

Thanks!

**Pull request merged**
