### PR TITLE
Suma/Nim/Flrtvc support for updating AIX TL/SP/Efix

### PR DESCRIPTION
**Pull request by robinvy**
### Description

Add support for sum, nim and flrtvc command. Allows update of machine in terms of SP/TL and Efix.
This is the same as #67 (closed) with new features and after merging chef-cookbooks/aix. It also fixes rubocop warnings.

### Issues Resolved

[List any existing issues this PR resolves]

### Check List

- [X] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [X] New functionality includes testing.
- [X] New functionality has been documented in the README if applicable
- [X] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by chmod666org** [comment]
@robinvy I can't merge the PR if Travis build has failed. Please check above. Thanks a lot.

**Comment by robinvy** [comment]
@chmod666org if I'm right, the 3 remaining Travis error are in 2 files that we didn't change: ./resources/inittab.rb and ./metadata.rb
Not sure what happened and how to fix, could you advise?

**Comment by chmod666org** [comment]
@robinvy Don't really know why you have to do it but I absolutely want to merge this PR. 
1/ in /metadata.rb change "Apache 2.0" to "Apache-2.0". This should fix the first two ones.
2/ Remove line 17 in /resources/inittab.rb
This should do the job.

**Comment by robinvy** [comment]
@chmod666org I tested locally that these 2 changes fix the 3 syntax complains. Unlike I was thinking, it seems I don't have write access to our repo aix-chef:master .
So I asked @Patrice-Atos to push these changes for me.
Thank you

**Comment by chmod666org** [comment]
@robinvy @Patrice-Atos It's merged. Thank a lot for you contribution. It's huge.

**Pull request merged**
